In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
df = pd.read_csv(r"C:\Users\PAUL\Desktop\dataset\Covidset.csv")

In [16]:
df = pd.read_csv(r"C:\Users\PAUL\Desktop\dataset\Covidset.csv")

In [17]:
df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
0,01/07/2020,1,7,2020,279,13,Afghanistan,AF,AFG,38041757.0,Asia
1,30/06/2020,30,6,2020,271,12,Afghanistan,AF,AFG,38041757.0,Asia
2,29/06/2020,29,6,2020,351,18,Afghanistan,AF,AFG,38041757.0,Asia
3,28/06/2020,28,6,2020,165,20,Afghanistan,AF,AFG,38041757.0,Asia
4,27/06/2020,27,6,2020,276,8,Afghanistan,AF,AFG,38041757.0,Asia

In [18]:
df.describe()

,day,month,year,cases,deaths,popData2019
count,26982.000000,26982.000000,26982.000000,26982.000000,26982.000000,2.691800e+04
mean,16.197873,4.230376,2019.997517,387.160070,18.939923,4.673026e+07
std,8.863097,1.570667,0.049770,2209.252863,121.212907,1.671715e+08
min,1.000000,1.000000,2019.000000,-2461.000000,-1918.000000,8.150000e+02
25%,9.000000,3.000000,2020.000000,0.000000,0.000000,1.919968e+06
50%,17.000000,4.000000,2020.000000,4.000000,0.000000,8.776119e+06
75%,24.000000,5.000000,2020.000000,69.000000,1.000000,3.182530e+07
max,31.000000,12.000000,2020.000000,54771.000000,4928.000000,1.433784e+09

In [19]:
df = df.drop(columns=["popData2019"])

In [20]:
df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,continentExp
0,01/07/2020,1,7,2020,279,13,Afghanistan,AF,AFG,Asia
1,30/06/2020,30,6,2020,271,12,Afghanistan,AF,AFG,Asia
2,29/06/2020,29,6,2020,351,18,Afghanistan,AF,AFG,Asia
3,28/06/2020,28,6,2020,165,20,Afghanistan,AF,AFG,Asia
4,27/06/2020,27,6,2020,276,8,Afghanistan,AF,AFG,Asia

In [21]:
df = df.drop(columns=["countryterritoryCode"])

In [22]:
df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,continentExp
0,01/07/2020,1,7,2020,279,13,Afghanistan,AF,Asia
1,30/06/2020,30,6,2020,271,12,Afghanistan,AF,Asia
2,29/06/2020,29,6,2020,351,18,Afghanistan,AF,Asia
3,28/06/2020,28,6,2020,165,20,Afghanistan,AF,Asia
4,27/06/2020,27,6,2020,276,8,Afghanistan,AF,Asia

In [23]:
df.to_csv("df_clean data.csv", index=False)